name = "davidm"
uuid = "36fb8131-d9cf-459b-9e5d-5b61eb169e68"
repo = "git@github.com:david-macmahon/MyJuliaRegistry"
description = "My not-yet-ready-for-General packages"

[packages]
6e31318f-3d89-4707-97ff-aaba23e5678c = { name = "BlioSpectroscopy", path = "B/BlioSpectroscopy" }
87855aa7-8b24-49b4-b316-97c011f78d17 = { name = "Blio", path = "B/Blio" }
