name = "davidm"
uuid = "36fb8131-d9cf-459b-9e5d-5b61eb169e68"
repo = "https://github.com/david-macmahon/MyJuliaRegistry"
description = "My not-yet-ready-for-General packages"

[packages]
5f96b823-c651-45d3-b54e-600e338e6562 = { name = "SeticoreCapnp", path = "S/SeticoreCapnp" }
6e2f7c64-92ce-42bb-83af-8f0e5f56b763 = { name = "HashpipeDatabufs", path = "H/HashpipeDatabufs" }
6e31318f-3d89-4707-97ff-aaba23e5678c = { name = "BlioSpectroscopy", path = "B/BlioSpectroscopy" }
751b3f49-6b1d-405b-83ce-d0b609eaf806 = { name = "UVH5Files", path = "U/UVH5Files" }
87855aa7-8b24-49b4-b316-97c011f78d17 = { name = "Blio", path = "B/Blio" }
947ddd50-af71-4e5f-8796-398fc6122734 = { name = "BeamformerRecipes", path = "B/BeamformerRecipes" }
9e73f634-81c6-42cf-8211-fb9f7b28b16d = { name = "INotify", path = "I/INotify" }
a3308ebd-878a-40c3-94ea-c874aaa84770 = { name = "FringeExplorer", path = "F/FringeExplorer" }
c0371cf2-69c1-404b-9565-f01b56f8974e = { name = "PyCASA", path = "P/PyCASA" }
d7a65883-3b66-4fe4-a274-f0f417c4cddf = { name = "RadioInterferometry", path = "R/RadioInterferometry" }
da57cb61-2122-4cb9-bf56-fd6f75f7b468 = { name = "PoolQueues", path = "P/PoolQueues" }
dce9cb67-2d69-4dbd-b3f2-02d6a32bde18 = { name = "DopplerDriftSearchPipelineOutputs", path = "D/DopplerDriftSearchPipelineOutputs" }
ee334479-6f21-49fc-a9ed-05530e45cd44 = { name = "BluseRawWatch", path = "B/BluseRawWatch" }
f722d36e-4eb8-44c6-8f06-e9434a5c3fdb = { name = "HpguppiDatabufs", path = "H/HpguppiDatabufs" }
fb54281b-2328-43f0-88b5-aa616f75139e = { name = "BLRemoteDataClient", path = "B/BLRemoteDataClient" }
ff10e4b9-378f-4bad-8d64-19def9d79a0d = { name = "BLRemoteDataServer", path = "B/BLRemoteDataServer" }
